// Audio slot definitions + validation flow roles, shared across admin / projection.
import { COMMUNES } from '@/lib/nodes';

// --- Validation flow (3 separate validator devices, in order) ---
export const ROLES = ['minister', 'pm', 'president'];

export const ROLE_LABEL = {
  minister: 'Ministre de la Santé',
  pm: 'Première Ministre',
  president: 'Président de la République',
};

// Validation/cinematic flow order. The President acts TWICE: first he INITIALISES
// (enters his code), the network initialises across the communes, then he CONFIRMS
// the ACTIVATION (a button), which launches the countdown → activation → video.
export const FLOW_ORDER = ['minister', 'pm', 'president', 'initializing', 'president_activate', 'launched'];

// Default codes (admin can change them in /admin).
export const DEFAULT_CODES = { minister: '111111', pm: '222222', president: '332003' };

// --- Audio slots ---
export const VALIDATION_SLOTS = [
  { key: 'validation_minister', label: 'Validation — Ministre de la Santé', group: 'Validation' },
  { key: 'validation_pm', label: 'Validation — Première Ministre', group: 'Validation' },
  { key: 'president_prompt', label: 'Invitation Président — INITIALISATION (« voulez-vous initialiser… »)', group: 'Validation' },
  { key: 'president_activate_prompt', label: 'Invitation Président — ACTIVATION (« confirmez-vous l’activation… »)', group: 'Validation' },
  { key: 'president_confirm', label: 'Confirmation d’activation (lancement)', group: 'Validation' },
];

export const PHASE_SLOTS = [
  { key: 'phase_analysis', label: 'Étape — Initialisation du système', group: 'Étapes' },
  { key: 'phase_validation', label: 'Étape — Initialisation engagée', group: 'Étapes' },
  { key: 'phase_deploy', label: 'Étape — Initialisation du réseau (intro)', group: 'Étapes' },
  { key: 'phase_init_done', label: 'Étape — Initialisation terminée (24 communes)', group: 'Étapes' },
  { key: 'phase_countdown', label: 'Étape — Lancement du compte à rebours', group: 'Étapes' },
  { key: 'phase_activation', label: 'Étape — Activation (199, opérationnel)', group: 'Étapes' },
];

// Spoken countdown 10 -> 1 (nothing is spoken at 0).
const COUNT_WORDS = { 10: 'Dix', 9: 'Neuf', 8: 'Huit', 7: 'Sept', 6: 'Six', 5: 'Cinq', 4: 'Quatre', 3: 'Trois', 2: 'Deux', 1: 'Un' };
export const COUNTDOWN_SLOTS = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1].map((n) => ({
  key: 'count_' + n, label: 'Compte à rebours — ' + n, group: 'Compte à rebours', count: n,
}));

export function communeSlot(i) { return 'commune_' + i; }

export const COMMUNE_SLOTS = COMMUNES.map((name, i) => ({
  key: communeSlot(i), label: 'Commune — ' + name, group: 'Communes', commune: name, index: i,
}));

// Sound design — generated by ElevenLabs (Music + Sound Effects) or uploaded.
// `sound: 'music' | 'sfx'` selects the generator; `prompt` is the default brief.
export const SOUND_SLOTS = [
  { key: 'bg_ambience', label: 'Musique de fond (boucle, sous toute la séquence)', group: 'Sons & Musique', noTts: true, sound: 'music', durationMs: 30000,
    prompt: 'Tense yet hopeful cinematic orchestral underscore for a solemn national ceremony, evolving warm strings, soft low brass swells, subtle pulsing heartbeat, no vocals, no heavy drums, seamless and loopable, dignified and modern.' },
  { key: 'sfx_validation', label: 'Effet — validation (à chaque code validé)', group: 'Sons & Musique', noTts: true, sound: 'sfx', duration: 2,
    prompt: 'Short futuristic confirmation chime, positive holographic UI success ping with a soft shimmer tail, clean and premium.' },
  { key: 'sfx_deploy', label: 'Effet — déploiement du réseau', group: 'Sons & Musique', noTts: true, sound: 'sfx', duration: 4,
    prompt: 'Sci-fi network activation sweep, energy spreading across a map, rising digital pulses and data shimmer, building forward momentum.' },
  { key: 'sfx_commune', label: 'Effet — après chaque commune (petit son)', group: 'Sons & Musique', noTts: true, sound: 'sfx', duration: 1,
    prompt: 'Short crisp digital confirmation blip, single soft UI beep with a tiny shimmer tail, very short and clean.' },
  { key: 'sfx_countdown', label: 'Effet — montée du compte à rebours', group: 'Sons & Musique', noTts: true, sound: 'sfx', duration: 5,
    prompt: 'Cinematic tension riser building to a climax over four seconds, rising orchestral and synth swell with accelerating ticks, ending right before an impact.' },
  { key: 'sting_activation', label: 'Sting — activation (au 199)', group: 'Sons & Musique', noTts: true, sound: 'sfx', duration: 5,
    prompt: 'Triumphant orchestral brass hit with a deep cinematic boom and bright shimmer, victorious heroic impact and reverb tail.' },
  { key: 'sfx_transition', label: 'Effet — bascule vers la vidéo', group: 'Sons & Musique', noTts: true, sound: 'sfx', duration: 3,
    prompt: 'Cinematic whoosh transition into a reveal, fast riser with a deep sub drop and a clean tail.' },
];

export const ALL_SLOTS = [...VALIDATION_SLOTS, ...PHASE_SLOTS, ...COUNTDOWN_SLOTS, ...COMMUNE_SLOTS, ...SOUND_SLOTS];

export const SLOT_GROUPS = ['Validation', 'Étapes', 'Compte à rebours', 'Communes', 'Sons & Musique'];

export function isValidSlot(key) {
  return ALL_SLOTS.some((s) => s.key === key);
}

// Suggested text for each TTS slot (prefilled in the admin, editable).
const TEXTS = {
  validation_minister: 'Validation faite par le Ministre de la Santé.',
  validation_pm: 'Validation faite par la Première Ministre.',
  president_prompt: 'Monsieur le Président, voulez-vous initialiser le système Étoile Bleue ?',
  president_activate_prompt: 'Monsieur le Président, confirmez-vous l’activation du système Étoile Bleue ?',
  president_confirm: 'Activation confirmée. Lancement du système Étoile Bleue.',
  phase_analysis: 'Initialisation du système Étoile Bleue en cours.',
  phase_validation: 'Initialisation engagée. Déploiement sur les communes de Kinshasa.',
  phase_deploy: 'Initialisation du réseau sur les vingt-quatre communes de Kinshasa.',
  phase_init_done: 'Le service Étoile Bleue a été initialisé dans les vingt-quatre communes de Kinshasa.',
  phase_countdown: 'Séquence d’activation engagée. Activation imminente.',
  phase_activation: 'Étoile Bleue est activé et lancé. Service opérationnel à cent pour cent dans la ville de Kinshasa.',
};

export function defaultText(key) {
  if (TEXTS[key]) return TEXTS[key];
  if (key && key.indexOf('commune_') === 0) {
    const i = parseInt(key.slice('commune_'.length), 10);
    const n = COMMUNES[i];
    return n ? ('Service initialisé à ' + n + '.') : '';
  }
  if (key && key.indexOf('count_') === 0) {
    const n = parseInt(key.slice('count_'.length), 10);
    return COUNT_WORDS[n] ? (COUNT_WORDS[n] + '.') : '';
  }
  return '';
}

// Fallback ElevenLabs pre-made voice IDs (used if the account voice list can't be fetched).
export const FALLBACK_VOICES = [
  { voice_id: 'pNInz6obpgDQGcFmaJgB', name: 'Adam (homme, grave)' },
  { voice_id: 'ErXwobaYiN019PkySvjV', name: 'Antoni (homme)' },
  { voice_id: 'TxGEqnHWrfWFTfGW9XjX', name: 'Josh (homme)' },
  { voice_id: 'VR6AewLTigWG4xSOukaG', name: 'Arnold (homme)' },
  { voice_id: '21m00Tcm4TlvDq8ikWAM', name: 'Rachel (femme)' },
  { voice_id: 'EXAVITQu4vr4xnSDxMaL', name: 'Bella (femme)' },
  { voice_id: 'AZnzlk1XvdvUeBnXmlld', name: 'Domi (femme)' },
  { voice_id: 'MF3mGyEYCl7XYWbV9V6O', name: 'Elli (femme)' },
];

export const DEFAULT_VOICE_ID = 'CHivAFig5q0FuNMEEmFi'; // Diba — French, African accent (announcer)
