// Server-side audio storage: writes generated bytes to Vercel Blob in production,
// or to public/uploads/ in local dev (no Blob token). Returns a public URL.
import { writeFile, mkdir } from 'fs/promises';
import path from 'path';

export async function storeAudioBytes(filename, buffer, contentType = 'audio/mpeg') {
  const safe = String(filename || 'audio').replace(/[^a-zA-Z0-9._-]/g, '_');
  if (process.env.BLOB_READ_WRITE_TOKEN) {
    const { put } = require('@vercel/blob');
    const blob = await put('audio/' + Date.now() + '-' + safe, buffer, {
      access: 'public', contentType, addRandomSuffix: true,
    });
    return { url: blob.url, pathname: blob.pathname, size: buffer.length };
  }
  // local dev fallback
  const rand = Math.random().toString(36).slice(2, 8);
  const fname = Date.now() + '-' + rand + '-' + safe;
  const dir = path.join(process.cwd(), 'public', 'uploads');
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, fname), buffer);
  return { url: '/uploads/' + fname, pathname: fname, size: buffer.length };
}
